### ISSUE TITLE
Replace Subgraph functionalities

### ISSUE THREAD

**Issue by MBadea17** [OceanProtocolEnterprise/ocean-node#15]
Subgraph functionalities being discontinued in ocean-node, we need to identify what Subgraph functionalities are needed in OE and define ways to implement them.

**Comment by FilipMasar** [comment]
@alexcos20 I would like to start the discussion about price caching. Right now we have DDO extended by a following structure in market
```
interface AccessDetails {
    type: 'fixed' | 'free' | 'NOT_SUPPORTED'
    price: string
    templateId: number
    addressOrId: string
    baseToken: TokenInfo
    datatoken: TokenInfo
    isPurchasable?: boolean
    isOwned: bool
    validOrderTx: string
    publisherMarketOrderFee: string
    validProviderFees?: ProviderFees
  }

interface TokenInfo {
  address: string
  name: string
  symbol: string
  decimals?: number
}
```
We would need something similar to have for every service.

Suggested actions from the call:
1. let's start by defining what exactly will be cached
2. hardcode some dummy values on right place in ocean-node - This will unblock other tasks (support multiple services in market, ..)
3. implement the proper logic of retrieving these pricing data - Something that @MarianButucel and his team can maybe work on

**Comment by Enghin84** [comment]
Subgraph queries from "market": https://docs.google.com/document/d/13-KgaNDL0Rt_Gkdyuh-I8gNPQ_7OsDOeW0MugYHjL8s/edit
