### ISSUE TITLE
[104] Improved compute infra payments

### ISSUE THREAD

**Issue by alexcos20** [OceanProtocolEnterprise/ocean-node#5]
Implement a new way for infrastructure payments to prevent over or underpayment for computation. E.g. credit or escrow systems via smart contracts.

- [ ] c2d escrow smart contract
- [ ] ocean node refactor
- [ ] c2d refactor
- [ ] ui changes

**Comment by MBadea17** [comment]
This will be implemented into the community version of Ocean Node.
